POST https://yds-eight.vercel.app/app/signup
Content-Type: application/json

{
    "firstName":"Shivam",
    "middleName": "Santoshbhai",
    "lastName": "Parekh",
    "address":"570, linden drive",
    "city":"Cambridge",
    "phone": 3653246481,
    "email":"Parekh@mail.com",
    "birthDate":"05-05-2000",
    "immigrationStatus":"WorkPermit",
    "collegeName": "Conestoga",
    "program": "IT",
    "campus": "Doon",
    "intake": "2021",
    "indiaName": "Santoshbhai",
    "indiaAddress": "Society",
    "indiaCity": "Surat",
    "indiaPhone": 123456789,
    "refName": "shiva",
    "refPhone": 123456789,
}
